import {
    autoGeneratedHashKey,
    rangeKey,
    table,
    attribute,
} from '@aws/dynamodb-data-mapper-annotations';

@table(process.env.DYNAMO_TABLE_NAME || `vc-demo-customer-table`)
export class Customer {
    @autoGeneratedHashKey()
    id: string;
    
    @attribute()
    createdAt: Date;

    @attribute()
    firstName: string;

    @attribute()
    lastName: string;
}